# Limpieza de Datos Sobre Videojuegos y Salud Mental

Este notebook se enfoca en la limpieza y preprocesamiento de un conjunto de datos relacionado con hábitos de juego, indicadores de salud mental, calidad del sueño y rendimiento académico en jugadores.

## Objetivos
- Limpiar datos inconsistentes
- Eliminar variables innecesarias
- Estandarizar valores categóricos
- Validar coherencia lógica entre métricas
- Preparar el dataset para visualización y análisis

## Carga del Dataset

El conjunto de datos es importado e inspeccionado para comprender su estructura, variables y posibles inconsistencias antes del proceso de limpieza. Una vez realizada la inspección, se modifican y se traducen los títulos para una mejor comprensión de parte del lector.

In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("gaming_mental_health.csv")

titulos = ["ID", "Edad", "Genero Jugador", "Horas Jugadas Diarias", "Genero Juego", "Juego Principal", "Plataforma Jugada", "Horas De Sueno", "Calidad De Sueno", "Interrupcion De Sueno", "Rendimiento Academico", "Notas", "Puntos Productividad Laboral", "Estado De Animo", "Frecuencia A Cambios De Humor", "Sindromes De Abstinencia", "Perdida De Otros Intereses", "Continuo A Pesar De Los Problemas", "Fatiga Visual", "Dolor De Espalda O Cuello", "Cambios En Peso Kg", "Horas De Ejercicio Semanalmente", "Puntos Aislamiento Social", "Horas De Encuentros Sociales Semanalmente", "Gastos En Juegos Mensualmente En Dolares", "Anos Jugando", "Riesgo De Adiccion A Los Juegos"]
df.columns = titulos
df.head()

,ID,Edad,Genero Jugador,Horas Jugadas Diarias,Genero Juego,Juego Principal,Plataforma Jugada,Horas De Sueno,Calidad De Sueno,Interrupcion De Sueno,...,Continuo A Pesar De Los Problemas,Fatiga Visual,Dolor De Espalda O Cuello,Cambios En Peso Kg,Horas De Ejercicio Semanalmente,Puntos Aislamiento Social,Horas De Encuentros Sociales Semanalmente,Gastos En Juegos Mensualmente En Dolares,Anos Jugando,Riesgo De Adiccion A Los Juegos
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

## Manejo de Valores Nulos

Se eliminan registros incompletos o con valores nulos para garantizar consistencia durante el análisis de datos.

In [25]:
df.dropna(subset = ['Notas','Puntos Productividad Laboral'], inplace=True)

## Selección de Variables

Se eliminan columnas poco relevantes o innecesarias con el fin de simplificar el dataset y enfocar el análisis en las variables principales.

In [26]:
elim_cols = ["Calidad De Sueno", "Interrupcion De Sueno","Puntos Productividad Laboral","Cambios En Peso Kg","Puntos Aislamiento Social","Gastos En Juegos Mensualmente En Dolares"]
df.drop(elim_cols, axis=1, inplace=True)
df

,ID,Edad,Genero Jugador,Horas Jugadas Diarias,Genero Juego,Juego Principal,Plataforma Jugada,Horas De Sueno,Rendimiento Academico,Notas,...,Frecuencia A Cambios De Humor,Sindromes De Abstinencia,Perdida De Otros Intereses,Continuo A Pesar De Los Problemas,Fatiga Visual,Dolor De Espalda O Cuello,Horas De Ejercicio Semanalmente,Horas De Encuentros Sociales Semanalmente,Anos Jugando,Riesgo De Adiccion A Los Juegos
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Good,3.75,...,Often,False,False,False,False,False,8.5,10.7,1,Low
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Poor,1.62,...,Daily,True,True,False,True,True,5.2,9.1,7,High
5,GD0006,21,Male,2.1,Mobile Games,Clash of Clans,PC,7.5,Good,3.81,...,Never,False,False,False,False,False,10.8,9.6,4,Low
6,GD0007,21,Male,2.7,FPS,Call of Duty,Multi-platform,7.2,Below Average,1.82,...,Rarely,False,False,False,False,False,10.0,10.1,3,Low
13,GD0014,22,Male,5.1,RPG,Skyrim,Mobile,5.3,Average,3.25,...,Rarely,False,False,False,True,False,7.6,6.3,5,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,GD0982,22,Female,13.6,Strategy,Civilization VI,Multi-platform,5.8,Failing,2.92,...,Often,True,True,False,True,False,2.4,0.0,2,Severe
987,GD0988,19,Male,4.7,MOBA,Dota 2,Console,6.7,Excellent,2.02,...,Often,False,False,False,False,False,6.5,9.0,9,Low
988,GD0989,20,Male,4.4,MMO,Final Fantasy XIV,PC,5.4,Good,2.26,...,Sometimes,False,False,False,False,False,9.7,12.1,7,Low
990,GD0991,19,Female,7.0,FPS,Valorant,PC,3.2,Poor,3.00,...,Daily,False,True,False,False,True,7.7,5.8,2,Moderate
994,GD0995,20,Female,9.3,Battle Royale,Apex Legends,Console,5.8,Poor,2.53,...,Never,False,True,True,False,False,4.4,6.1,10,Severe

## Traducción de Variables y Valores

Se realizó la traducción de nombres de columnas y valores categóricos originalmente en inglés al español con el objetivo de mejorar la comprensión, legibilidad y consistencia general del dataset durante el proceso de análisis.

In [27]:
df["Genero Jugador"] = df["Genero Jugador"].replace({"Male":"Masculino","Female":"Femenino","Other":"Otro"})
df["Plataforma Jugada"] = df["Plataforma Jugada"].replace({"Multi-platform":"Multi-platforma","Console":"Consola","Mobile":"Celular"})
df["Genero Juego"] = df["Genero Juego"].replace({"Strategy":"Estrategia","Mobile Games":"Juegos De Celular"})
df

,ID,Edad,Genero Jugador,Horas Jugadas Diarias,Genero Juego,Juego Principal,Plataforma Jugada,Horas De Sueno,Rendimiento Academico,Notas,...,Frecuencia A Cambios De Humor,Sindromes De Abstinencia,Perdida De Otros Intereses,Continuo A Pesar De Los Problemas,Fatiga Visual,Dolor De Espalda O Cuello,Horas De Ejercicio Semanalmente,Horas De Encuentros Sociales Semanalmente,Anos Jugando,Riesgo De Adiccion A Los Juegos
1,GD0002,21,Masculino,3.0,MOBA,Dota 2,PC,7.2,Good,3.75,...,Often,False,False,False,False,False,8.5,10.7,1,Low
3,GD0004,20,Femenino,7.2,RPG,Skyrim,Multi-platforma,5.1,Poor,1.62,...,Daily,True,True,False,True,True,5.2,9.1,7,High
5,GD0006,21,Masculino,2.1,Juegos De Celular,Clash of Clans,PC,7.5,Good,3.81,...,Never,False,False,False,False,False,10.8,9.6,4,Low
6,GD0007,21,Masculino,2.7,FPS,Call of Duty,Multi-platforma,7.2,Below Average,1.82,...,Rarely,False,False,False,False,False,10.0,10.1,3,Low
13,GD0014,22,Masculino,5.1,RPG,Skyrim,Celular,5.3,Average,3.25,...,Rarely,False,False,False,True,False,7.6,6.3,5,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,GD0982,22,Femenino,13.6,Estrategia,Civilization VI,Multi-platforma,5.8,Failing,2.92,...,Often,True,True,False,True,False,2.4,0.0,2,Severe
987,GD0988,19,Masculino,4.7,MOBA,Dota 2,Consola,6.7,Excellent,2.02,...,Often,False,False,False,False,False,6.5,9.0,9,Low
988,GD0989,20,Masculino,4.4,MMO,Final Fantasy XIV,PC,5.4,Good,2.26,...,Sometimes,False,False,False,False,False,9.7,12.1,7,Low
990,GD0991,19,Femenino,7.0,FPS,Valorant,PC,3.2,Poor,3.00,...,Daily,False,True,False,False,True,7.7,5.8,2,Moderate
994,GD0995,20,Femenino,9.3,Battle Royale,Apex Legends,Consola,5.8,Poor,2.53,...,Never,False,True,True,False,False,4.4,6.1,10,Severe

## Validación de Calidad del Sueño

Las categorías relacionadas con la calidad del sueño fueron reajustadas según las horas de sueño registradas para mejorar la coherencia lógica de los datos.

In [28]:

bins = [0, 4, 5.5, 6.5, 8, 10]
labels = ["Muy Baja", "Baja", "Intermedia", "Buena", "Muy buena"]

df["Calidad Sueno"] = pd.cut(
    df["Horas De Sueno"],
    bins=bins,
    labels=labels,
    right=False
)

df[["Horas De Sueno", "Calidad Sueno"]].head(10)

    Horas De Sueno Calidad Sueno
1              7.2         Buena
3              5.1          Baja
5              7.5         Buena
6              7.2         Buena
13             5.3          Baja
14             5.2          Baja
16             7.4         Buena
17             4.6          Baja
18             3.2      Muy Baja
19             5.5    Intermedia

In [29]:
df["Calidad Sueno"] = df["Calidad Sueno"].astype(str)
df.info()

<class 'pandas.DataFrame'>
Index: 428 entries, 1 to 994
Data columns (total 22 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         428 non-null    str
 1   Edad                                       428 non-null    int64
 2   Genero Jugador                             428 non-null    str
 3   Horas Jugadas Diarias                      428 non-null    float64
 4   Genero Juego                               428 non-null    str
 5   Juego Principal                            428 non-null    str
 6   Plataforma Jugada                          428 non-null    str
 7   Horas De Sueno                             428 non-null    float64
 8   Rendimiento Academico                      428 non-null    str
 9   Notas                                      428 non-null    float64
 10  Estado De Animo                            428 non-null    str
 11  Frecuencia A Cambios De Humor              428 non-null    str
 12  Sindromes De Abstinencia                   428 non-null    bool
 13  Perdida De Otros Intereses                 428 non-null    bool
 14  Continuo A Pesar De Los Problemas          428 non-null    bool
 15  Fatiga Visual                              428 non-null    bool
 16  Dolor De Espalda O Cuello                  428 non-null    bool
 17  Horas De Ejercicio Semanalmente            428 non-null    float64
 18  Horas De Encuentros Sociales Semanalmente  428 non-null    float64
 19  Anos Jugando                               428 non-null    int64
 20  Riesgo De Adiccion A Los Juegos            428 non-null    str
 21  Calidad Sueno                              428 non-null    str
dtypes: bool(5), float64(5), int64(2), str(10)
memory usage: 62.3 KB

## Validación del Rendimiento Académico

Las categorías de rendimiento académico fueron recalculadas a partir de las notas obtenidas para reducir inconsistencias entre variables numéricas y categóricas.

In [30]:
df[["Rendimiento Academico", "Notas"]].head(10)

   Rendimiento Academico  Notas
1                   Good   3.75
3                   Poor   1.62
5                   Good   3.81
6          Below Average   1.82
13               Average   3.25
14                  Good   2.54
16                  Poor   1.64
17                  Poor   1.89
18               Average   2.76
19         Below Average   2.14

In [31]:
bins = [0, 2.5, 3, 4, 4.5, 5.1]
labels = ["Insuficiente", "Bajo", "Medio", "Alto", "Superior"]

df["Rendimiento Academico"] = pd.cut(
    df["Notas"],
    bins=bins,
    labels=labels,
    right=False
)

df["Rendimiento Academico"].value_counts()

Rendimiento Academico
Insuficiente    220
Medio           145
Bajo             63
Alto              0
Superior          0
Name: count, dtype: int64

In [32]:
df[["Rendimiento Academico", "Notas"]].head(10)

   Rendimiento Academico  Notas
1                  Medio   3.75
3           Insuficiente   1.62
5                  Medio   3.81
6           Insuficiente   1.82
13                 Medio   3.25
14                  Bajo   2.54
16          Insuficiente   1.64
17          Insuficiente   1.89
18                  Bajo   2.76
19          Insuficiente   2.14

### Observación

Durante el proceso de limpieza se identificaron inconsistencias entre algunas variables categóricas y sus respectivos valores numéricos, por lo que fue necesario realizar ajustes para mejorar la calidad del dataset.

## Dataset Final

El conjunto de datos se encuentra limpio, estandarizado y preparado para procesos posteriores de análisis exploratorio y visualización.

In [33]:
df.to_csv("gaming_mental_health_cleaning.csv", index=False)